--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 11.0.1106
--  Created On : sábado, 25 abril, 2015 
--  DBMS       : SQL Server 2012 
--  -------------------------------------------------- 

CREATE TABLE Usuario ( 
	UsuarioID int identity(1,1)  NOT NULL,    -- ID do Usuário 
	Apelido varchar(25) NOT NULL,    -- Apelido do usuário 
	Nome varchar(100) NOT NULL,    -- Nome do usuário 
	Senha varchar(32) NOT NULL,    -- Senha do usuário (a senha é armazenada em MD5) 
	Email varchar(100),    -- Email do usuário 
	Ativo bit DEFAULT 1 NOT NULL,    -- Informa se o usuário é ativo 
	Sistema bit DEFAULT 0 NOT NULL    -- Informa se o usuário é o administrador do sistema 
);

ALTER TABLE Usuario
	ADD CONSTRAINT UQ_Usuario_Apelido UNIQUE (Apelido);

ALTER TABLE Usuario
	ADD CONSTRAINT UQ_Usuario_UsuarioID UNIQUE (UsuarioID);

CREATE INDEX IX_Usuario_Apelido
	ON Usuario (Apelido ASC);

ALTER TABLE Usuario ADD CONSTRAINT PK_Usuario 
	PRIMARY KEY CLUSTERED (UsuarioID);

EXEC sp_addextendedproperty 'MS_Description', 'Relação de usuários do sistema.', 'Schema', dbo, 'table', Usuario;
EXEC sp_addextendedproperty 'MS_Description', 'ID do Usuário', 'Schema', dbo, 'table', Usuario, 'column', UsuarioID;

EXEC sp_addextendedproperty 'MS_Description', 'Apelido do usuário', 'Schema', dbo, 'table', Usuario, 'column', Apelido;

EXEC sp_addextendedproperty 'MS_Description', 'Nome do usuário', 'Schema', dbo, 'table', Usuario, 'column', Nome;

EXEC sp_addextendedproperty 'MS_Description', 'Senha do usuário
(a senha é armazenada em MD5)', 'Schema', dbo, 'table', Usuario, 'column', Senha;

EXEC sp_addextendedproperty 'MS_Description', 'Email do usuário', 'Schema', dbo, 'table', Usuario, 'column', Email;

EXEC sp_addextendedproperty 'MS_Description', 'Informa se o usuário é ativo', 'Schema', dbo, 'table', Usuario, 'column', Ativo;

EXEC sp_addextendedproperty 'MS_Description', 'Informa se o usuário é o administrador do sistema', 'Schema', dbo, 'table', Usuario, 'column', Sistema;

