///////////////////////////////////////////////////////////
//  Conta.cs
//  Implementation of the Class Conta
//  Generated by Enterprise Architect
//  Created on:      01-mai-2015 21:49:21
//  Original author: Elcio
///////////////////////////////////////////////////////////

using System;

namespace Modelos
{
    /// <summary>
    /// Contas do sistema
    /// </summary>
    public class Conta {

        /// <summary>
        /// ID da Conta
        /// </summary>
        private int _contaID;
        /// <summary>
        /// ID do usuário que incluiu a conta.
        /// </summary>
        private int _usuarioID;
        /// <summary>
        /// Instituição onde a conta é mantida.
        /// </summary>
        private int? _instituicaoID;
        /// <summary>
        /// Tipo de conta.
        /// </summary>
        private int? _tipoContaID;
        /// <summary>
        /// Moeda utilizada nessa conta.
        /// </summary>
        private int? _moedaID;
        /// <summary>
        /// Apelido da conta.
        /// </summary>
        private string _apelido;
        /// <summary>
        /// Descrição da conta
        /// </summary>
        private string _descricao;
        /// <summary>
        /// Data de abertura.
        /// </summary>
        private DateTime? _dataAbertura;
        /// <summary>
        /// Saldo na abertura da conta.
        /// </summary>
        private decimal? _saldoInicial;
        /// <summary>
        /// Limite da conta.
        /// </summary>
        private decimal? _limite;
        /// <summary>
        /// Informa se a conta é ativa ou não.
        /// </summary>
        private bool _ativo = true;
        /// <summary>
        /// Informa se a conta permite investimentos a partir dela.
        /// (caso negativo, o recurso deberá ser transferido para outra conta que permite)
        /// </summary>
        private bool _permiteInvestimento = false;
        private bool _OFX = false;
        private int _decimais = 2;
        private bool _usaHora = false;
        private bool _exibirProjecao = false;
        private bool _CSV = false;
        private string _TipoArquivo;


        public int ContaID
        {
            get { return _contaID; }
            set { _contaID = value; }
        }

        public int UsuarioID
        {
            get { return _usuarioID; }
            set { _usuarioID = value; }
        }

        public int? InstituicaoID
        {
            get { return _instituicaoID; }
            set { _instituicaoID = value; }
        }

        public int? MoedaID
        {
            get { return _moedaID; }
            set { _moedaID = value; }
        }

        public int? TipoContaID
        {
            get { return _tipoContaID; }
            set { _tipoContaID = value; }
        }

        public string Apelido
        {
            get { return _apelido; }
            set { _apelido = value; }
        }

        public string Descricao
        {
            get { return _descricao; }
            set { _descricao = value; }
        }

        public DateTime? DataAbertura
        {
            get { return _dataAbertura; }
            set { _dataAbertura = value; }
        }

        public decimal? SaldoInicial
        {
            get { return _saldoInicial; }
            set { _saldoInicial = value; }
        }

        public decimal? Limite
        {
            get { return _limite; }
            set { _limite = value; }
        }

        public bool Ativo
        {
            get { return _ativo; }
            set { _ativo = value; }
        }

        public bool PermiteInvestimento
        {
            get { return _permiteInvestimento; }
            set { _permiteInvestimento = value; }
        }

        public bool OFX
        {
            get { return _OFX; }
            set { _OFX = value; }
        }

        public int Decimais
        {
            get { return _decimais; }
            set { _decimais = value; }
        }

        public bool UsaHora
        {
            get { return _usaHora; }
            set { _usaHora = value; }
        }

        public bool ExibirProjecao
        {
            get { return _exibirProjecao; }
            set { _exibirProjecao = value; }
        }

        public bool CSV
        {
            get { return _CSV; }
            set { _CSV = value; }
        }

        public string TipoArquivo
        {
            get { return _TipoArquivo; }
            set { _TipoArquivo = value; }
        }

    }//end Conta

}//end namespace Classes