///////////////////////////////////////////////////////////
//  GrupoConta.cs
//  Implementation of the Class GrupoConta
//  Generated by Enterprise Architect
//  Created on:      26-abr-2015 09:23:36
//  Original author: Elcio
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace Modelos
{
    /// <summary>
    /// Grupo de Contas, para agrupar por:
    /// -Disponível
    /// -Reserva
    /// -Crédito
    /// -Investimentos
    /// -Bens e Direitos
    /// -Deveres
    /// </summary>
    public class GrupoConta
    {

        /// <summary>
        /// ID do Grupo de Conta
        /// </summary>
        private int _grupoContaID;
        /// <summary>
        /// Usuário que criou o grupo.
        /// </summary>
        private int _usuarioID;
        /// <summary>
        /// Apelido do grupo de contas
        /// </summary>
        private string _apelido;
        /// <summary>
        /// Descrição do grupo de contas
        /// </summary>
        private string _descricao;
        /// <summary>
        /// Ordem de apresentação em tela.
        /// </summary>
        private int _ordem;
        /// <summary>
        /// Define se ativo ou não.
        /// </summary>
        private bool _ativo = true;


        /// <summary>
        /// Propriedade para manipular _grupoContaID.
        /// </summary>
        public int GrupoContaID
        {
            get { return _grupoContaID; }
            set { _grupoContaID = value; }
        }

        /// <summary>
        /// Propriedade para manipular _usuarioID.
        /// </summary>
        public int UsuarioID
        {
            get { return _usuarioID; }
            set { _usuarioID = value; }
        }

        /// <summary>
        /// Propriedade para manipular _apelido.
        /// </summary>
        public string Apelido
        {
            get { return _apelido; }
            set { _apelido = value; }
        }

        /// <summary>
        /// Propriedade para manipular _descricao.
        /// </summary>
        public string Descricao
        {
            get { return _descricao; }
            set { _descricao = value; }
        }

        /// <summary>
        /// Propriedade para manipular _ordem.
        /// </summary>
        public int Ordem
        {
            get { return _ordem; }
            set { _ordem = value; }
        }

        /// <summary>
        /// Propriedade para manipular _ativo.
        /// </summary>
        public bool Ativo
        {
            get { return _ativo; }
            set { _ativo = value; }
        }

    }//end GrupoConta

}//end namespace Classes