///////////////////////////////////////////////////////////
//  Instituicao.cs
//  Implementation of the Class Instituicao
//  Generated by Enterprise Architect
//  Created on:      01-mai-2015 10:14:01
//  Original author: Elcio
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace Modelos
{
	/// <summary>
	/// Instituições onde são mantidas as contas.
	/// </summary>
	public class Instituicao
    {

		/// <summary>
		/// ID da instituição
		/// </summary>
		private int _instituicaoID;
		/// <summary>
		/// Usuário que incluiu a instituição.
		/// </summary>
		private int _usuarioID;
		/// <summary>
		/// Identifica o tipo de instituição financeira.
		/// </summary>
		private int? _tipoInstituicaoID;
		/// <summary>
		/// Apelido da Instituição
		/// </summary>
		private string _apelido;
		/// <summary>
		/// Descrição da instituição
		/// </summary>
		private string _descricao;
		/// <summary>
		/// Número do banco, conforme FEBRABAN
		/// (preencher apenas se for banco)
		/// </summary>
		private int? _banco;
		/// <summary>
		/// Informa se o banco está ou não ativo.
		/// </summary>
		private bool _ativo = true;

		public int InstituicaoID
        {
            get { return _instituicaoID; }
            set { _instituicaoID = value; }
		}

		public int UsuarioID
        {
            get { return _usuarioID; }
            set { _usuarioID = value; }
		}

		public int? TipoInstituicaoID
        {
            get { return _tipoInstituicaoID; }
            set { _tipoInstituicaoID = value; }
		}

		public string Apelido
        {
            get { return _apelido; }
            set { _apelido = value; }
		}

		public string Descricao
        {
            get { return _descricao; }
            set { _descricao = value; }
		}

		public int? Banco
        {
            get { return _banco; }
            set { _banco = value; }
		}

		public bool Ativo
        {
            get { return _ativo; }
            set { _ativo = value; }
		}

	}//end Instituicao

}//end namespace Classes