///////////////////////////////////////////////////////////
//  TipoInstituicao.cs
//  Implementation of the Class TipoInstituicao
//  Generated by Enterprise Architect
//  Created on:      30-abr-2015 20:27:43
//  Original author: Elcio
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Modelos
{

    /// <summary>
    /// Tipo de instituição.
    /// </summary>
    public class TipoInstituicao
    {

        /// <summary>
        /// ID do Tipo Instituição
        /// </summary>
        private int _tipoInstituicaoID;
        /// <summary>
        /// Usuário que criou o tipo de instituição.
        /// </summary>
        private int _usuarioID;
        /// <summary>
        /// Apelido do Tipo de Instituição
        /// </summary>
        private string _apelido;
        /// <summary>
        /// Descrição do tipo de instituição.
        /// </summary>
        private string _descricao;
        /// <summary>
        /// Define se o tipo de instituição é ativo ou inativo.
        /// </summary>
        private bool _ativo = true;

        public int TipoInstituicaoID
        {
            get { return _tipoInstituicaoID; }
            set { _tipoInstituicaoID = value; }
        }

        public int UsuarioID
        {
            get { return _usuarioID; }
            set { _usuarioID = value; }
        }

        public string Apelido
        {
            get { return _apelido; }
            set { _apelido = value; }
        }

        public bool Ativo
        {
            get { return _ativo; }
            set { _ativo = value; }
        }

        public string Descricao
        {
            get { return _descricao; }
            set { _descricao = value; }
        }

    }//end TipoInstituicao

}//end namespace Classes