//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyPro.ServiceReferenceCVM {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cvm.gov.br/webservices/", ConfigurationName="ServiceReferenceCVM.WsDownloadInfsSoap")]
    public interface WsDownloadInfsSoap {
        
        // CODEGEN: Gerando contrato de mensagem porque a mensagem retornaListaComptcDocsRequest tem cabeçalhos
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaListaComptcDocs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsResponse retornaListaComptcDocs(MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaListaComptcDocs", ReplyAction="*")]
        System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsResponse> retornaListaComptcDocsAsync(MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a mensagem retornaListaComptcDocsParticRequest tem cabeçalhos
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaListaComptcDocsPartic", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsParticResponse retornaListaComptcDocsPartic(MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsParticRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaListaComptcDocsPartic", ReplyAction="*")]
        System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsParticResponse> retornaListaComptcDocsParticAsync(MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsParticRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a mensagem retornaListaComptcDocsAdmRequest tem cabeçalhos
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaListaComptcDocsAdm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsAdmResponse retornaListaComptcDocsAdm(MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsAdmRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaListaComptcDocsAdm", ReplyAction="*")]
        System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsAdmResponse> retornaListaComptcDocsAdmAsync(MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsAdmRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a mensagem solicAutorizDownloadCadastroRequest tem cabeçalhos
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadCadastro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MoneyPro.ServiceReferenceCVM.solicAutorizDownloadCadastroResponse solicAutorizDownloadCadastro(MoneyPro.ServiceReferenceCVM.solicAutorizDownloadCadastroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadCadastro", ReplyAction="*")]
        System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.solicAutorizDownloadCadastroResponse> solicAutorizDownloadCadastroAsync(MoneyPro.ServiceReferenceCVM.solicAutorizDownloadCadastroRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a mensagem solicAutorizDownloadArqComptcRequest tem cabeçalhos
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadArqComptc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqComptcResponse solicAutorizDownloadArqComptc(MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqComptcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadArqComptc", ReplyAction="*")]
        System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqComptcResponse> solicAutorizDownloadArqComptcAsync(MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqComptcRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a mensagem solicAutorizDownloadArqEntregaRequest tem cabeçalhos
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadArqEntrega", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqEntregaResponse solicAutorizDownloadArqEntrega(MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqEntregaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadArqEntrega", ReplyAction="*")]
        System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqEntregaResponse> solicAutorizDownloadArqEntregaAsync(MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqEntregaRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a mensagem solicAutorizDownloadArqEntregaPorDataRequest tem cabeçalhos
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadArqEntregaPorData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqEntregaPorDataResponse solicAutorizDownloadArqEntregaPorData(MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqEntregaPorDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadArqEntregaPorData", ReplyAction="*")]
        System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqEntregaPorDataResponse> solicAutorizDownloadArqEntregaPorDataAsync(MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqEntregaPorDataRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a mensagem solicAutorizDownloadArqAnualRequest tem cabeçalhos
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadArqAnual", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqAnualResponse solicAutorizDownloadArqAnual(MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqAnualRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadArqAnual", ReplyAction="*")]
        System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqAnualResponse> solicAutorizDownloadArqAnualAsync(MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqAnualRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a mensagem retornaDtLmtEntrDocsArqsDispRequest tem cabeçalhos
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaDtLmtEntrDocsArqsDisp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MoneyPro.ServiceReferenceCVM.retornaDtLmtEntrDocsArqsDispResponse retornaDtLmtEntrDocsArqsDisp(MoneyPro.ServiceReferenceCVM.retornaDtLmtEntrDocsArqsDispRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaDtLmtEntrDocsArqsDisp", ReplyAction="*")]
        System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.retornaDtLmtEntrDocsArqsDispResponse> retornaDtLmtEntrDocsArqsDispAsync(MoneyPro.ServiceReferenceCVM.retornaDtLmtEntrDocsArqsDispRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a mensagem retornaListaDownloadDocsRequest tem cabeçalhos
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaListaDownloadDocs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MoneyPro.ServiceReferenceCVM.retornaListaDownloadDocsResponse retornaListaDownloadDocs(MoneyPro.ServiceReferenceCVM.retornaListaDownloadDocsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaListaDownloadDocs", ReplyAction="*")]
        System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.retornaListaDownloadDocsResponse> retornaListaDownloadDocsAsync(MoneyPro.ServiceReferenceCVM.retornaListaDownloadDocsRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a mensagem LoginRequest tem cabeçalhos
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MoneyPro.ServiceReferenceCVM.LoginResponse Login(MoneyPro.ServiceReferenceCVM.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.LoginResponse> LoginAsync(MoneyPro.ServiceReferenceCVM.LoginRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
    public partial class sessaoIdHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string guidField;
        
        private int idSessaoField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
                this.RaisePropertyChanged("Guid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IdSessao {
            get {
                return this.idSessaoField;
            }
            set {
                this.idSessaoField = value;
                this.RaisePropertyChanged("IdSessao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaListaComptcDocs", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaListaComptcDocsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iCdTpDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strDtIniEntregDoc;
        
        public retornaListaComptcDocsRequest() {
        }
        
        public retornaListaComptcDocsRequest(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtIniEntregDoc) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iCdTpDoc = iCdTpDoc;
            this.strDtIniEntregDoc = strDtIniEntregDoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaListaComptcDocsResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaListaComptcDocsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string[] retornaListaComptcDocsResult;
        
        public retornaListaComptcDocsResponse() {
        }
        
        public retornaListaComptcDocsResponse(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, string[] retornaListaComptcDocsResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.retornaListaComptcDocsResult = retornaListaComptcDocsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaListaComptcDocsPartic", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaListaComptcDocsParticRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iCdTpDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strDtIniEntregDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=2)]
        public string strNrPfPj;
        
        public retornaListaComptcDocsParticRequest() {
        }
        
        public retornaListaComptcDocsParticRequest(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtIniEntregDoc, string strNrPfPj) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iCdTpDoc = iCdTpDoc;
            this.strDtIniEntregDoc = strDtIniEntregDoc;
            this.strNrPfPj = strNrPfPj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaListaComptcDocsParticResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaListaComptcDocsParticResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string[] retornaListaComptcDocsParticResult;
        
        public retornaListaComptcDocsParticResponse() {
        }
        
        public retornaListaComptcDocsParticResponse(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, string[] retornaListaComptcDocsParticResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.retornaListaComptcDocsParticResult = retornaListaComptcDocsParticResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaListaComptcDocsAdm", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaListaComptcDocsAdmRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iCdTpDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strDtIniEntregDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=2)]
        public string strNrPfPj;
        
        public retornaListaComptcDocsAdmRequest() {
        }
        
        public retornaListaComptcDocsAdmRequest(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtIniEntregDoc, string strNrPfPj) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iCdTpDoc = iCdTpDoc;
            this.strDtIniEntregDoc = strDtIniEntregDoc;
            this.strNrPfPj = strNrPfPj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaListaComptcDocsAdmResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaListaComptcDocsAdmResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string[] retornaListaComptcDocsAdmResult;
        
        public retornaListaComptcDocsAdmResponse() {
        }
        
        public retornaListaComptcDocsAdmResponse(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, string[] retornaListaComptcDocsAdmResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.retornaListaComptcDocsAdmResult = retornaListaComptcDocsAdmResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadCadastro", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadCadastroRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string strDtRefer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strMotivoAutorizDownload;
        
        public solicAutorizDownloadCadastroRequest() {
        }
        
        public solicAutorizDownloadCadastroRequest(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, string strDtRefer, string strMotivoAutorizDownload) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.strDtRefer = strDtRefer;
            this.strMotivoAutorizDownload = strMotivoAutorizDownload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadCadastroResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadCadastroResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string solicAutorizDownloadCadastroResult;
        
        public solicAutorizDownloadCadastroResponse() {
        }
        
        public solicAutorizDownloadCadastroResponse(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, string solicAutorizDownloadCadastroResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.solicAutorizDownloadCadastroResult = solicAutorizDownloadCadastroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadArqComptc", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadArqComptcRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iCdTpDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strDtComptcDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=2)]
        public string strMotivoAutorizDownload;
        
        public solicAutorizDownloadArqComptcRequest() {
        }
        
        public solicAutorizDownloadArqComptcRequest(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtComptcDoc, string strMotivoAutorizDownload) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iCdTpDoc = iCdTpDoc;
            this.strDtComptcDoc = strDtComptcDoc;
            this.strMotivoAutorizDownload = strMotivoAutorizDownload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadArqComptcResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadArqComptcResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string solicAutorizDownloadArqComptcResult;
        
        public solicAutorizDownloadArqComptcResponse() {
        }
        
        public solicAutorizDownloadArqComptcResponse(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, string solicAutorizDownloadArqComptcResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.solicAutorizDownloadArqComptcResult = solicAutorizDownloadArqComptcResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadArqEntrega", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadArqEntregaRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iCdTpDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strMotivoAutorizDownload;
        
        public solicAutorizDownloadArqEntregaRequest() {
        }
        
        public solicAutorizDownloadArqEntregaRequest(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strMotivoAutorizDownload) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iCdTpDoc = iCdTpDoc;
            this.strMotivoAutorizDownload = strMotivoAutorizDownload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadArqEntregaResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadArqEntregaResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string solicAutorizDownloadArqEntregaResult;
        
        public solicAutorizDownloadArqEntregaResponse() {
        }
        
        public solicAutorizDownloadArqEntregaResponse(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, string solicAutorizDownloadArqEntregaResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.solicAutorizDownloadArqEntregaResult = solicAutorizDownloadArqEntregaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadArqEntregaPorData", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadArqEntregaPorDataRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iCdTpDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strDtEntregaDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=2)]
        public string strMotivoAutorizDownload;
        
        public solicAutorizDownloadArqEntregaPorDataRequest() {
        }
        
        public solicAutorizDownloadArqEntregaPorDataRequest(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtEntregaDoc, string strMotivoAutorizDownload) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iCdTpDoc = iCdTpDoc;
            this.strDtEntregaDoc = strDtEntregaDoc;
            this.strMotivoAutorizDownload = strMotivoAutorizDownload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadArqEntregaPorDataResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadArqEntregaPorDataResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string solicAutorizDownloadArqEntregaPorDataResult;
        
        public solicAutorizDownloadArqEntregaPorDataResponse() {
        }
        
        public solicAutorizDownloadArqEntregaPorDataResponse(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, string solicAutorizDownloadArqEntregaPorDataResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.solicAutorizDownloadArqEntregaPorDataResult = solicAutorizDownloadArqEntregaPorDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadArqAnual", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadArqAnualRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iCdTpDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strMotivoAutorizDownload;
        
        public solicAutorizDownloadArqAnualRequest() {
        }
        
        public solicAutorizDownloadArqAnualRequest(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strMotivoAutorizDownload) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iCdTpDoc = iCdTpDoc;
            this.strMotivoAutorizDownload = strMotivoAutorizDownload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadArqAnualResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadArqAnualResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string solicAutorizDownloadArqAnualResult;
        
        public solicAutorizDownloadArqAnualResponse() {
        }
        
        public solicAutorizDownloadArqAnualResponse(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, string solicAutorizDownloadArqAnualResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.solicAutorizDownloadArqAnualResult = solicAutorizDownloadArqAnualResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaDtLmtEntrDocsArqsDisp", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaDtLmtEntrDocsArqsDispRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iCdTpDoc;
        
        public retornaDtLmtEntrDocsArqsDispRequest() {
        }
        
        public retornaDtLmtEntrDocsArqsDispRequest(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iCdTpDoc) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iCdTpDoc = iCdTpDoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaDtLmtEntrDocsArqsDispResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaDtLmtEntrDocsArqsDispResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string retornaDtLmtEntrDocsArqsDispResult;
        
        public retornaDtLmtEntrDocsArqsDispResponse() {
        }
        
        public retornaDtLmtEntrDocsArqsDispResponse(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, string retornaDtLmtEntrDocsArqsDispResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.retornaDtLmtEntrDocsArqsDispResult = retornaDtLmtEntrDocsArqsDispResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaListaDownloadDocs", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaListaDownloadDocsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iCdTpPartic;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strNrPfPj;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=2)]
        public int iCdTpDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=3)]
        public string strDtIni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=4)]
        public string strDtFim;
        
        public retornaListaDownloadDocsRequest() {
        }
        
        public retornaListaDownloadDocsRequest(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iCdTpPartic, string strNrPfPj, int iCdTpDoc, string strDtIni, string strDtFim) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iCdTpPartic = iCdTpPartic;
            this.strNrPfPj = strNrPfPj;
            this.iCdTpDoc = iCdTpDoc;
            this.strDtIni = strDtIni;
            this.strDtFim = strDtFim;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaListaDownloadDocsResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaListaDownloadDocsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string[] retornaListaDownloadDocsResult;
        
        public retornaListaDownloadDocsResponse() {
        }
        
        public retornaListaDownloadDocsResponse(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, string[] retornaListaDownloadDocsResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.retornaListaDownloadDocsResult = retornaListaDownloadDocsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iNrSist;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strSenha;
        
        public LoginRequest() {
        }
        
        public LoginRequest(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iNrSist, string strSenha) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iNrSist = iNrSist;
            this.strSenha = strSenha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader;
        
        public LoginResponse() {
        }
        
        public LoginResponse(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader) {
            this.sessaoIdHeader = sessaoIdHeader;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsDownloadInfsSoapChannel : MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsDownloadInfsSoapClient : System.ServiceModel.ClientBase<MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap>, MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap {
        
        public WsDownloadInfsSoapClient() {
        }
        
        public WsDownloadInfsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsDownloadInfsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsDownloadInfsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsDownloadInfsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsResponse MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap.retornaListaComptcDocs(MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsRequest request) {
            return base.Channel.retornaListaComptcDocs(request);
        }
        
        public string[] retornaListaComptcDocs(ref MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtIniEntregDoc) {
            MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsRequest inValue = new MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtIniEntregDoc = strDtIniEntregDoc;
            MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsResponse retVal = ((MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap)(this)).retornaListaComptcDocs(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.retornaListaComptcDocsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsResponse> MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap.retornaListaComptcDocsAsync(MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsRequest request) {
            return base.Channel.retornaListaComptcDocsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsResponse> retornaListaComptcDocsAsync(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtIniEntregDoc) {
            MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsRequest inValue = new MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtIniEntregDoc = strDtIniEntregDoc;
            return ((MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap)(this)).retornaListaComptcDocsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsParticResponse MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap.retornaListaComptcDocsPartic(MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsParticRequest request) {
            return base.Channel.retornaListaComptcDocsPartic(request);
        }
        
        public string[] retornaListaComptcDocsPartic(ref MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtIniEntregDoc, string strNrPfPj) {
            MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsParticRequest inValue = new MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsParticRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtIniEntregDoc = strDtIniEntregDoc;
            inValue.strNrPfPj = strNrPfPj;
            MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsParticResponse retVal = ((MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap)(this)).retornaListaComptcDocsPartic(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.retornaListaComptcDocsParticResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsParticResponse> MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap.retornaListaComptcDocsParticAsync(MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsParticRequest request) {
            return base.Channel.retornaListaComptcDocsParticAsync(request);
        }
        
        public System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsParticResponse> retornaListaComptcDocsParticAsync(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtIniEntregDoc, string strNrPfPj) {
            MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsParticRequest inValue = new MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsParticRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtIniEntregDoc = strDtIniEntregDoc;
            inValue.strNrPfPj = strNrPfPj;
            return ((MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap)(this)).retornaListaComptcDocsParticAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsAdmResponse MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap.retornaListaComptcDocsAdm(MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsAdmRequest request) {
            return base.Channel.retornaListaComptcDocsAdm(request);
        }
        
        public string[] retornaListaComptcDocsAdm(ref MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtIniEntregDoc, string strNrPfPj) {
            MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsAdmRequest inValue = new MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsAdmRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtIniEntregDoc = strDtIniEntregDoc;
            inValue.strNrPfPj = strNrPfPj;
            MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsAdmResponse retVal = ((MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap)(this)).retornaListaComptcDocsAdm(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.retornaListaComptcDocsAdmResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsAdmResponse> MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap.retornaListaComptcDocsAdmAsync(MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsAdmRequest request) {
            return base.Channel.retornaListaComptcDocsAdmAsync(request);
        }
        
        public System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsAdmResponse> retornaListaComptcDocsAdmAsync(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtIniEntregDoc, string strNrPfPj) {
            MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsAdmRequest inValue = new MoneyPro.ServiceReferenceCVM.retornaListaComptcDocsAdmRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtIniEntregDoc = strDtIniEntregDoc;
            inValue.strNrPfPj = strNrPfPj;
            return ((MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap)(this)).retornaListaComptcDocsAdmAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MoneyPro.ServiceReferenceCVM.solicAutorizDownloadCadastroResponse MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap.solicAutorizDownloadCadastro(MoneyPro.ServiceReferenceCVM.solicAutorizDownloadCadastroRequest request) {
            return base.Channel.solicAutorizDownloadCadastro(request);
        }
        
        public string solicAutorizDownloadCadastro(ref MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, string strDtRefer, string strMotivoAutorizDownload) {
            MoneyPro.ServiceReferenceCVM.solicAutorizDownloadCadastroRequest inValue = new MoneyPro.ServiceReferenceCVM.solicAutorizDownloadCadastroRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.strDtRefer = strDtRefer;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            MoneyPro.ServiceReferenceCVM.solicAutorizDownloadCadastroResponse retVal = ((MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap)(this)).solicAutorizDownloadCadastro(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.solicAutorizDownloadCadastroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.solicAutorizDownloadCadastroResponse> MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap.solicAutorizDownloadCadastroAsync(MoneyPro.ServiceReferenceCVM.solicAutorizDownloadCadastroRequest request) {
            return base.Channel.solicAutorizDownloadCadastroAsync(request);
        }
        
        public System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.solicAutorizDownloadCadastroResponse> solicAutorizDownloadCadastroAsync(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, string strDtRefer, string strMotivoAutorizDownload) {
            MoneyPro.ServiceReferenceCVM.solicAutorizDownloadCadastroRequest inValue = new MoneyPro.ServiceReferenceCVM.solicAutorizDownloadCadastroRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.strDtRefer = strDtRefer;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            return ((MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap)(this)).solicAutorizDownloadCadastroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqComptcResponse MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap.solicAutorizDownloadArqComptc(MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqComptcRequest request) {
            return base.Channel.solicAutorizDownloadArqComptc(request);
        }
        
        public string solicAutorizDownloadArqComptc(ref MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtComptcDoc, string strMotivoAutorizDownload) {
            MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqComptcRequest inValue = new MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqComptcRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtComptcDoc = strDtComptcDoc;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqComptcResponse retVal = ((MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap)(this)).solicAutorizDownloadArqComptc(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.solicAutorizDownloadArqComptcResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqComptcResponse> MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap.solicAutorizDownloadArqComptcAsync(MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqComptcRequest request) {
            return base.Channel.solicAutorizDownloadArqComptcAsync(request);
        }
        
        public System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqComptcResponse> solicAutorizDownloadArqComptcAsync(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtComptcDoc, string strMotivoAutorizDownload) {
            MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqComptcRequest inValue = new MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqComptcRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtComptcDoc = strDtComptcDoc;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            return ((MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap)(this)).solicAutorizDownloadArqComptcAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqEntregaResponse MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap.solicAutorizDownloadArqEntrega(MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqEntregaRequest request) {
            return base.Channel.solicAutorizDownloadArqEntrega(request);
        }
        
        public string solicAutorizDownloadArqEntrega(ref MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strMotivoAutorizDownload) {
            MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqEntregaRequest inValue = new MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqEntregaRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqEntregaResponse retVal = ((MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap)(this)).solicAutorizDownloadArqEntrega(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.solicAutorizDownloadArqEntregaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqEntregaResponse> MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap.solicAutorizDownloadArqEntregaAsync(MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqEntregaRequest request) {
            return base.Channel.solicAutorizDownloadArqEntregaAsync(request);
        }
        
        public System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqEntregaResponse> solicAutorizDownloadArqEntregaAsync(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strMotivoAutorizDownload) {
            MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqEntregaRequest inValue = new MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqEntregaRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            return ((MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap)(this)).solicAutorizDownloadArqEntregaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqEntregaPorDataResponse MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap.solicAutorizDownloadArqEntregaPorData(MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqEntregaPorDataRequest request) {
            return base.Channel.solicAutorizDownloadArqEntregaPorData(request);
        }
        
        public string solicAutorizDownloadArqEntregaPorData(ref MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtEntregaDoc, string strMotivoAutorizDownload) {
            MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqEntregaPorDataRequest inValue = new MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqEntregaPorDataRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtEntregaDoc = strDtEntregaDoc;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqEntregaPorDataResponse retVal = ((MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap)(this)).solicAutorizDownloadArqEntregaPorData(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.solicAutorizDownloadArqEntregaPorDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqEntregaPorDataResponse> MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap.solicAutorizDownloadArqEntregaPorDataAsync(MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqEntregaPorDataRequest request) {
            return base.Channel.solicAutorizDownloadArqEntregaPorDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqEntregaPorDataResponse> solicAutorizDownloadArqEntregaPorDataAsync(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtEntregaDoc, string strMotivoAutorizDownload) {
            MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqEntregaPorDataRequest inValue = new MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqEntregaPorDataRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtEntregaDoc = strDtEntregaDoc;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            return ((MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap)(this)).solicAutorizDownloadArqEntregaPorDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqAnualResponse MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap.solicAutorizDownloadArqAnual(MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqAnualRequest request) {
            return base.Channel.solicAutorizDownloadArqAnual(request);
        }
        
        public string solicAutorizDownloadArqAnual(ref MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strMotivoAutorizDownload) {
            MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqAnualRequest inValue = new MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqAnualRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqAnualResponse retVal = ((MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap)(this)).solicAutorizDownloadArqAnual(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.solicAutorizDownloadArqAnualResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqAnualResponse> MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap.solicAutorizDownloadArqAnualAsync(MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqAnualRequest request) {
            return base.Channel.solicAutorizDownloadArqAnualAsync(request);
        }
        
        public System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqAnualResponse> solicAutorizDownloadArqAnualAsync(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strMotivoAutorizDownload) {
            MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqAnualRequest inValue = new MoneyPro.ServiceReferenceCVM.solicAutorizDownloadArqAnualRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            return ((MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap)(this)).solicAutorizDownloadArqAnualAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MoneyPro.ServiceReferenceCVM.retornaDtLmtEntrDocsArqsDispResponse MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap.retornaDtLmtEntrDocsArqsDisp(MoneyPro.ServiceReferenceCVM.retornaDtLmtEntrDocsArqsDispRequest request) {
            return base.Channel.retornaDtLmtEntrDocsArqsDisp(request);
        }
        
        public string retornaDtLmtEntrDocsArqsDisp(ref MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iCdTpDoc) {
            MoneyPro.ServiceReferenceCVM.retornaDtLmtEntrDocsArqsDispRequest inValue = new MoneyPro.ServiceReferenceCVM.retornaDtLmtEntrDocsArqsDispRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            MoneyPro.ServiceReferenceCVM.retornaDtLmtEntrDocsArqsDispResponse retVal = ((MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap)(this)).retornaDtLmtEntrDocsArqsDisp(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.retornaDtLmtEntrDocsArqsDispResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.retornaDtLmtEntrDocsArqsDispResponse> MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap.retornaDtLmtEntrDocsArqsDispAsync(MoneyPro.ServiceReferenceCVM.retornaDtLmtEntrDocsArqsDispRequest request) {
            return base.Channel.retornaDtLmtEntrDocsArqsDispAsync(request);
        }
        
        public System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.retornaDtLmtEntrDocsArqsDispResponse> retornaDtLmtEntrDocsArqsDispAsync(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iCdTpDoc) {
            MoneyPro.ServiceReferenceCVM.retornaDtLmtEntrDocsArqsDispRequest inValue = new MoneyPro.ServiceReferenceCVM.retornaDtLmtEntrDocsArqsDispRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            return ((MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap)(this)).retornaDtLmtEntrDocsArqsDispAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MoneyPro.ServiceReferenceCVM.retornaListaDownloadDocsResponse MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap.retornaListaDownloadDocs(MoneyPro.ServiceReferenceCVM.retornaListaDownloadDocsRequest request) {
            return base.Channel.retornaListaDownloadDocs(request);
        }
        
        public string[] retornaListaDownloadDocs(ref MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iCdTpPartic, string strNrPfPj, int iCdTpDoc, string strDtIni, string strDtFim) {
            MoneyPro.ServiceReferenceCVM.retornaListaDownloadDocsRequest inValue = new MoneyPro.ServiceReferenceCVM.retornaListaDownloadDocsRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpPartic = iCdTpPartic;
            inValue.strNrPfPj = strNrPfPj;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtIni = strDtIni;
            inValue.strDtFim = strDtFim;
            MoneyPro.ServiceReferenceCVM.retornaListaDownloadDocsResponse retVal = ((MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap)(this)).retornaListaDownloadDocs(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.retornaListaDownloadDocsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.retornaListaDownloadDocsResponse> MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap.retornaListaDownloadDocsAsync(MoneyPro.ServiceReferenceCVM.retornaListaDownloadDocsRequest request) {
            return base.Channel.retornaListaDownloadDocsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.retornaListaDownloadDocsResponse> retornaListaDownloadDocsAsync(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iCdTpPartic, string strNrPfPj, int iCdTpDoc, string strDtIni, string strDtFim) {
            MoneyPro.ServiceReferenceCVM.retornaListaDownloadDocsRequest inValue = new MoneyPro.ServiceReferenceCVM.retornaListaDownloadDocsRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpPartic = iCdTpPartic;
            inValue.strNrPfPj = strNrPfPj;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtIni = strDtIni;
            inValue.strDtFim = strDtFim;
            return ((MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap)(this)).retornaListaDownloadDocsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MoneyPro.ServiceReferenceCVM.LoginResponse MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap.Login(MoneyPro.ServiceReferenceCVM.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public void Login(ref MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iNrSist, string strSenha) {
            MoneyPro.ServiceReferenceCVM.LoginRequest inValue = new MoneyPro.ServiceReferenceCVM.LoginRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iNrSist = iNrSist;
            inValue.strSenha = strSenha;
            MoneyPro.ServiceReferenceCVM.LoginResponse retVal = ((MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap)(this)).Login(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.LoginResponse> MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap.LoginAsync(MoneyPro.ServiceReferenceCVM.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<MoneyPro.ServiceReferenceCVM.LoginResponse> LoginAsync(MoneyPro.ServiceReferenceCVM.sessaoIdHeader sessaoIdHeader, int iNrSist, string strSenha) {
            MoneyPro.ServiceReferenceCVM.LoginRequest inValue = new MoneyPro.ServiceReferenceCVM.LoginRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iNrSist = iNrSist;
            inValue.strSenha = strSenha;
            return ((MoneyPro.ServiceReferenceCVM.WsDownloadInfsSoap)(this)).LoginAsync(inValue);
        }
    }
}
