--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 11.0.1106
--  Created On : sábado, 25 abril, 2015 
--  DBMS       : SQL Server 2012 
--  -------------------------------------------------- 

CREATE TABLE Categoria ( 
	CategoriaID int identity(1,1)  NOT NULL,    -- ID da Categoria 
	UsuarioID int,    -- Usuário que criou a categoria 
	Apelido varchar(25) NOT NULL,    -- Apelido da categoria. 
	Descricao varchar(100),    -- Descrição da categoria. 
	CategoriaPaiID int,    -- Chave estrangeira autoreferenciada. 
	GrupoCategoriaID int,    -- Informa a qual grupo de categorias a categoria pertence. É opcional 
	CrdDeb char(1) NOT NULL,    -- Informa se é crédito ou débito ou branco caso seja transferência. 
	OrdemVisual int,    -- Identifica a ordem de exibição das categorias pai.  (categoria cujo campo CategoriaPaiID é nulo). 
	Fixo bit DEFAULT 0 NOT NULL,    -- Define se a categoria é uma conta fixa. 
	Ativo bit DEFAULT 1 NOT NULL,    -- Informa se a categoria é ativa ou não. 
	ContaID int,    -- Se a categoria está ligada a uma conta. Categorias ligadas a contas são usadas para transferência. 
	Sistema bit NOT NULL    -- Informa se o registro foi criado pelo sistema. 
);

ALTER TABLE Categoria
	ADD CONSTRAINT UQ_Categoria_CategoriaID UNIQUE (CategoriaID);

CREATE UNIQUE INDEX IX_Categoria_CategoriaPai_Apelido
	ON Categoria (GrupoCategoriaID ASC, Apelido ASC);

ALTER TABLE Categoria ADD CONSTRAINT PK_Categoria 
	PRIMARY KEY CLUSTERED (CategoriaID);

ALTER TABLE Categoria ADD CONSTRAINT FK_Categoria_Categoria 
	FOREIGN KEY (CategoriaPaiID) REFERENCES Categoria (CategoriaID);

ALTER TABLE Categoria ADD CONSTRAINT FK_Categoria_Usuario 
	FOREIGN KEY (UsuarioID) REFERENCES Usuario (UsuarioID);

EXEC sp_addextendedproperty 'MS_Description', 'Categoria dos lançamentos em conta.
Exemplo:
-Alimentação
-Alimentação:Refeição
-Alimentação:Restaurante
-Automóvel
-Automóvel:Combustível', 'Schema', dbo, 'table', Categoria;
EXEC sp_addextendedproperty 'MS_Description', 'ID da Categoria', 'Schema', dbo, 'table', Categoria, 'column', CategoriaID;

EXEC sp_addextendedproperty 'MS_Description', 'Usuário que criou a categoria', 'Schema', dbo, 'table', Categoria, 'column', UsuarioID;

EXEC sp_addextendedproperty 'MS_Description', 'Apelido da categoria.', 'Schema', dbo, 'table', Categoria, 'column', Apelido;

EXEC sp_addextendedproperty 'MS_Description', 'Descrição da categoria.', 'Schema', dbo, 'table', Categoria, 'column', Descricao;

EXEC sp_addextendedproperty 'MS_Description', 'Chave estrangeira autoreferenciada.', 'Schema', dbo, 'table', Categoria, 'column', CategoriaPaiID;

EXEC sp_addextendedproperty 'MS_Description', 'Informa a qual grupo de categorias a categoria pertence.
É opcional', 'Schema', dbo, 'table', Categoria, 'column', GrupoCategoriaID;

EXEC sp_addextendedproperty 'MS_Description', 'Informa se é crédito ou débito ou branco caso seja transferência.', 'Schema', dbo, 'table', Categoria, 'column', CrdDeb;

EXEC sp_addextendedproperty 'MS_Description', 'Identifica a ordem de exibição das categorias pai. 
(categoria cujo campo CategoriaPaiID é nulo).', 'Schema', dbo, 'table', Categoria, 'column', OrdemVisual;

EXEC sp_addextendedproperty 'MS_Description', 'Define se a categoria é uma conta fixa.', 'Schema', dbo, 'table', Categoria, 'column', Fixo;

EXEC sp_addextendedproperty 'MS_Description', 'Informa se a categoria é ativa ou não.', 'Schema', dbo, 'table', Categoria, 'column', Ativo;

EXEC sp_addextendedproperty 'MS_Description', 'Se a categoria está ligada a uma conta.
Categorias ligadas a contas são usadas para transferência.', 'Schema', dbo, 'table', Categoria, 'column', ContaID;

EXEC sp_addextendedproperty 'MS_Description', 'Informa se o registro foi criado pelo sistema.', 'Schema', dbo, 'table', Categoria, 'column', Sistema;

