--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 11.0.1106
--  Created On : sábado, 25 abril, 2015 
--  DBMS       : SQL Server 2012 
--  -------------------------------------------------- 

CREATE TABLE GrupoCategoria ( 
	GrupoCategoriaID int identity(1,1)  NOT NULL,    -- ID do Grupo 
	UsuarioID int,    -- Usuário que criou o grupo. 
	Apelido varchar(25) NOT NULL,    -- Apelido do grupo 
	Descricao varchar(100),    -- Descrição do grupo 
	Ativo bit DEFAULT 1 NOT NULL    -- Informa se o grupo está ou não ativo. 
);

ALTER TABLE GrupoCategoria
	ADD CONSTRAINT UQ_GrupoCategoria_GrupoCategoriaID UNIQUE (GrupoCategoriaID);

ALTER TABLE GrupoCategoria
	ADD CONSTRAINT UQ_Grupo_Apelido UNIQUE (Apelido);

CREATE INDEX IX_GrupoCategoria_Apelido
	ON GrupoCategoria (Apelido ASC);

ALTER TABLE GrupoCategoria ADD CONSTRAINT PK_Grupo 
	PRIMARY KEY CLUSTERED (GrupoCategoriaID);

ALTER TABLE GrupoCategoria ADD CONSTRAINT FK_GrupoCategoria_Usuario 
	FOREIGN KEY (UsuarioID) REFERENCES Usuario (UsuarioID);

EXEC sp_addextendedproperty 'MS_Description', 'Grupo de categorias.', 'Schema', dbo, 'table', GrupoCategoria;
EXEC sp_addextendedproperty 'MS_Description', 'ID do Grupo', 'Schema', dbo, 'table', GrupoCategoria, 'column', GrupoCategoriaID;

EXEC sp_addextendedproperty 'MS_Description', 'Usuário que criou o grupo.', 'Schema', dbo, 'table', GrupoCategoria, 'column', UsuarioID;

EXEC sp_addextendedproperty 'MS_Description', 'Apelido do grupo', 'Schema', dbo, 'table', GrupoCategoria, 'column', Apelido;

EXEC sp_addextendedproperty 'MS_Description', 'Descrição do grupo', 'Schema', dbo, 'table', GrupoCategoria, 'column', Descricao;

EXEC sp_addextendedproperty 'MS_Description', 'Informa se o grupo está ou não ativo.', 'Schema', dbo, 'table', GrupoCategoria, 'column', Ativo;

